import type { Lesson } from "./types";

export const localLessons: Lesson[] = [
  {
    id: "local-rreshti-baze",
    slug: "rreshti-baze",
    title: "Rreshti baze",
    description: "Nis me tastet kryesore per pozicion stabil.",
    targetKeys: ["a", "s", "d", "f", "j", "k", "l"],
    exerciseText: "a s d f j k l as df jk la sa fa ja ka al",
    orderIndex: 1,
    requiredAccuracy: 90,
    requiredWpm: 12,
    bestWpm: 0,
    bestAccuracy: 0,
    completed: false,
    attempts: 0,
    unlocked: true,
    progress: 0
  },
  {
    id: "local-dora-e-majte",
    slug: "dora-e-majte",
    title: "Dora e majte",
    description: "Forco levizjen e tastave me doren e majte.",
    targetKeys: ["q", "w", "e", "r", "t", "a", "s", "d", "f"],
    exerciseText: "a s d f q w e r t as de fr ta we qa sad fad red water",
    orderIndex: 2,
    requiredAccuracy: 91,
    requiredWpm: 14,
    bestWpm: 0,
    bestAccuracy: 0,
    completed: false,
    attempts: 0,
    unlocked: true,
    progress: 0
  },
  {
    id: "local-dora-e-djathte",
    slug: "dora-e-djathte",
    title: "Dora e djathte",
    description: "Nderto kontroll me tastet e anes se djathte.",
    targetKeys: ["y", "u", "i", "o", "p", "j", "k", "l"],
    exerciseText: "j k l y u i o p ju ki lo py uj ok jo pik lu",
    orderIndex: 3,
    requiredAccuracy: 91,
    requiredWpm: 14,
    bestWpm: 0,
    bestAccuracy: 0,
    completed: false,
    attempts: 0,
    unlocked: true,
    progress: 0
  },
  {
    id: "local-rreshti-i-siperm",
    slug: "rreshti-i-siperm",
    title: "Rreshti i siperm",
    description: "Praktiko q w e r t y u i o p me rithem.",
    targetKeys: ["q", "w", "e", "r", "t", "y", "u", "i", "o", "p"],
    exerciseText: "q w e r t y u i o p te re ui po try our wire prior",
    orderIndex: 4,
    requiredAccuracy: 92,
    requiredWpm: 16,
    bestWpm: 0,
    bestAccuracy: 0,
    completed: false,
    attempts: 0,
    unlocked: false,
    progress: 0
  },
  {
    id: "local-rreshti-i-poshtem",
    slug: "rreshti-i-poshtem",
    title: "Rreshti i poshtem",
    description: "Mbaj duart te qeta gjate z x c v b n m.",
    targetKeys: ["z", "x", "c", "v", "b", "n", "m"],
    exerciseText: "z x c v b n m mz cv bn nx zv mb vencim zonim",
    orderIndex: 5,
    requiredAccuracy: 92,
    requiredWpm: 16,
    bestWpm: 0,
    bestAccuracy: 0,
    completed: false,
    attempts: 0,
    unlocked: false,
    progress: 0
  },
  {
    id: "local-numrat",
    slug: "numrat",
    title: "Numrat",
    description: "Ushtro numra dhe seri te shkurtra.",
    targetKeys: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "0"],
    exerciseText: "1 2 3 4 5 6 7 8 9 0 12 34 56 78 90 2026 5173",
    orderIndex: 6,
    requiredAccuracy: 92,
    requiredWpm: 15,
    bestWpm: 0,
    bestAccuracy: 0,
    completed: false,
    attempts: 0,
    unlocked: false,
    progress: 0
  },
  {
    id: "local-simbolet",
    slug: "simbolet",
    title: "Simbolet",
    description: "Praktiko shenja te perdorura shpesh.",
    targetKeys: [".", ",", ";", ":", "-", "_", "(", ")"],
    exerciseText: "test, tekst. ritmi; saktesi: fokus - plan _ kod (data) api",
    orderIndex: 7,
    requiredAccuracy: 93,
    requiredWpm: 14,
    bestWpm: 0,
    bestAccuracy: 0,
    completed: false,
    attempts: 0,
    unlocked: false,
    progress: 0
  },
  {
    id: "local-fjale-te-shkurtra",
    slug: "fjale-te-shkurtra",
    title: "Fjale te shkurtra",
    description: "Rrit ritmin me fjale te shkurtra.",
    targetKeys: ["a", "e", "i", "o", "u"],
    exerciseText: "une jam sot pak mire pune kohe test kod app faqe",
    orderIndex: 8,
    requiredAccuracy: 94,
    requiredWpm: 20,
    bestWpm: 0,
    bestAccuracy: 0,
    completed: false,
    attempts: 0,
    unlocked: false,
    progress: 0
  },
  {
    id: "local-fjali-te-plota",
    slug: "fjali-te-plota",
    title: "Fjali te plota",
    description: "Shkruaj fjali me qartesi dhe rithem.",
    targetKeys: ["all"],
    exerciseText: "une shkruaj me kujdes dhe ruaj saktesi ne cdo fjali te re",
    orderIndex: 9,
    requiredAccuracy: 95,
    requiredWpm: 24,
    bestWpm: 0,
    bestAccuracy: 0,
    completed: false,
    attempts: 0,
    unlocked: false,
    progress: 0
  },
  {
    id: "local-shpejtesi-dhe-saktesi",
    slug: "shpejtesi-dhe-saktesi",
    title: "Shpejtesi dhe saktesi",
    description: "Finalizo me test te balancuar.",
    targetKeys: ["all"],
    exerciseText: "shpejtesia e mire vjen kur saktesia mbetet e larte edhe nen presion",
    orderIndex: 10,
    requiredAccuracy: 96,
    requiredWpm: 30,
    bestWpm: 0,
    bestAccuracy: 0,
    completed: false,
    attempts: 0,
    unlocked: false,
    progress: 0
  }
];
